#!/bin/bash
# Go Chat Completion One-Liners
# Randomly selects and speaks a witty one-liner when Claude finishes working

one_liners=(
    "Go chat, go!"
    "Chat complete, go celebrate."
    "The go chat has spoken."
    "Go forth and chat."
    "Chat's all folks!"
    "Go chat yourself."
    "Ready to go chat the world."
    "The chat has gone."
    "Go chat or go home."
    "Chat delivered, go relax."
    "That was one good chat to go."
    "Go chat your heart out."
    "Chat accomplished, ready to go."
    "The go chat is on fire."
    "Go team chat!"
    "Chat and go, that's the flow."
    "Ready, set, go chat!"
    "Go chat like the wind."
    "The chat is strong with this one."
    "Go chat boldly."
    "Chat's done, time to go."
    "Go chat to the moon."
    "Another chat gone, another victory."
    "Go chat conquers again."
    "The chat must go on."
    "Go chat saves the day."
    "Chat like a go pro."
    "Go big or go chat."
    "Chat first, go later."
    "The legendary go chat strikes again."
    "Go chat does it again."
    "Chat mode: complete. Go mode: activated."
    "Go chat never disappoints."
    "That chat was ready to go."
    "Go chat for the win."
    "Chat complete. Go time."
    "The go chat prevails."
    "Go chat: mission accomplished."
    "Chat away, go play."
    "Go chat rising."
    "All chat systems go."
    "Go chat to infinity."
    "Chat locked, ready to go."
    "Go chat strikes gold."
    "The chat that keeps on going."
    "Go chat and prosper."
    "Chat's the way to go."
    "Go chat masterclass complete."
    "Smooth chat, smooth go."
    "Go chat at your service."
    "Chat excellence, go greatness."
    "The go chat experience."
    "Chat wrapped, ready to go."
    "Go chat vibes only."
    "Another day, another go chat."
    "Chat like there's no tomorrow, go!"
    "Go chat magic in action."
    "The art of go chat."
    "Chat done right, go feel light."
    "Go chat levels unlocked."
    "Chat with me, go with glee."
    "Go chat domination."
    "The go chat way."
    "Chat today, go slay."
    "Go chat revolution."
    "Chat goals: crushed. Go goals: next."
    "The unstoppable go chat."
    "Go chat perfection achieved."
    "Chat's what I call a good go."
    "Go chat in full swing."
    "Chat the talk, go the walk."
    "Go chat sensation."
    "Another chat, another go around."
    "Chat like a champ, go like a boss."
    "Go chat energy unleashed."
    "The chat to go."
    "Go chat made it happen."
    "Chat smart, go far."
    "Go chat wonder."
    "Chat complete, mission go."
    "Go chat brings the heat."
    "That's what I call go chat."
    "Chat done, fun begun, go on."
    "Go chat in the zone."
    "The one and only go chat."
    "Chat brilliance, go excellence."
    "Go chat dreams realized."
    "Chat mastery, go history."
    "Go chat stands tall."
    "Chat victory, go glory."
    "The epic go chat saga continues."
    "Go chat: simply the best."
    "Chat flows, go grows."
    "Go chat making moves."
    "Chat wrapped with a bow, ready to go."
    "Go chat legendary status."
    "Chat power, go hour."
    "The go chat chronicles."
    "Chat delivered, go achieved."
    "Go chat out."
)

# Pick random one-liner
random_index=$((RANDOM % ${#one_liners[@]}))
one_liner="${one_liners[$random_index]}"

# Speak it using default macOS voice
say "$one_liner"
